/**
 * Claude Stage Adapter
 *
 * Writes to `.claude/CLAUDE.md` — a subdirectory-scoped instruction
 * file. Claude Code lazy-loads CLAUDE.md from subdirectories only
 * when working on files in that directory, avoiding global injection.
 */

import fs from "fs/promises";
import path from "path";

export interface ClaudeStageInput {
    /** Tal persona thinking/description */
    persona: string;
    /** Full dance rules text (includes skills if present) */
    rules: string;
    /** Optional act description */
    actDescription?: string;
}

/**
 * Write a scoped CLAUDE.md file for Claude Code.
 */
export async function applyClaudeStage(
    cwd: string,
    input: ClaudeStageInput
): Promise<string> {
    const dir = path.join(cwd, ".claude");
    await fs.mkdir(dir, { recursive: true });

    const filePath = path.join(dir, "CLAUDE.md");

    const sections: string[] = [
        `# Dance of Tal — AI Behavior Rules`,
        "",
        `## Persona`,
        input.persona,
        "",
        `## Rules`,
        input.rules,
    ];

    if (input.actDescription) {
        sections.push("", `## Workflow`, input.actDescription);
    }

    sections.push(
        "",
        `<!-- Generated by Dance of Tal (dot) — do not edit manually -->`
    );

    await fs.writeFile(filePath, sections.join("\n"), "utf-8");
    return path.relative(cwd, filePath);
}
