/**
 * Codex Stage Adapter
 *
 * Writes to `.codex/agents/dot-<combo>.md` — a subdirectory-scoped
 * agent instruction file. Codex cascades AGENTS.md from nearest dir
 * to project root, so we place it in a scoped subdirectory.
 */

import fs from "fs/promises";
import path from "path";

export interface CodexStageInput {
    /** Tal persona thinking/description */
    persona: string;
    /** Full dance rules text (includes skills if present) */
    rules: string;
    /** Optional act description */
    actDescription?: string;
    /** Combo name for file naming */
    comboName?: string;
}

/**
 * Write a scoped agent instruction file for Codex.
 */
export async function applyCodexStage(
    cwd: string,
    input: CodexStageInput
): Promise<string> {
    const comboSlug = input.comboName || "combo";
    const dir = path.join(cwd, ".codex", "agents");
    await fs.mkdir(dir, { recursive: true });

    const filename = `dot-${comboSlug}.md`;
    const filePath = path.join(dir, filename);

    const sections: string[] = [
        `# Dance of Tal — AI Behavior Rules`,
        "",
        `## Persona`,
        input.persona,
        "",
        `## Rules`,
        input.rules,
    ];

    if (input.actDescription) {
        sections.push("", `## Workflow`, input.actDescription);
    }

    sections.push(
        "",
        `<!-- Generated by Dance of Tal (dot) — do not edit manually -->`
    );

    await fs.writeFile(filePath, sections.join("\n"), "utf-8");
    return path.relative(cwd, filePath);
}
