/**
 * Cursor / Windsurf Stage Adapter
 *
 * Cursor: Writes to `.cursor/rules/dot-<combo>.mdc` — scoped MDC file
 *         with frontmatter so the AI activates it conditionally, not globally.
 * Windsurf: Writes to `.windsurfrules` — project root (no scoped alternative).
 */

import fs from "fs/promises";
import path from "path";

export type CursorVariant = "cursor" | "windsurf";

export interface CursorStageInput {
    /** Tal persona thinking/description */
    persona: string;
    /** Full dance rules text (includes skills if present) */
    rules: string;
    /** Optional act description */
    actDescription?: string;
    /** Combo name for file naming */
    comboName?: string;
}

/**
 * Build the markdown body shared by all rule-file adapters.
 */
function buildSections(input: CursorStageInput): string {
    const sections: string[] = [
        `# Dance of Tal — AI Behavior Rules`,
        "",
        `## Persona`,
        input.persona,
        "",
        `## Rules`,
        input.rules,
    ];

    if (input.actDescription) {
        sections.push("", `## Workflow`, input.actDescription);
    }

    sections.push(
        "",
        `<!-- Generated by Dance of Tal (dot) — do not edit manually -->`
    );

    return sections.join("\n");
}

/**
 * Write a scoped rules file for Cursor or Windsurf.
 */
export async function applyCursorStage(
    cwd: string,
    variant: CursorVariant,
    input: CursorStageInput
): Promise<string> {
    const body = buildSections(input);
    const comboSlug = input.comboName || "combo";

    if (variant === "cursor") {
        // Scoped: .cursor/rules/dot-<combo>.mdc with MDC frontmatter
        const dir = path.join(cwd, ".cursor", "rules");
        await fs.mkdir(dir, { recursive: true });
        const filename = `dot-${comboSlug}.mdc`;
        const filePath = path.join(dir, filename);

        const mdcContent = [
            `---`,
            `description: Dance of Tal combo (${comboSlug}) — persona, rules, and workflow`,
            `globs: "**"`,
            `alwaysApply: false`,
            `---`,
            "",
            body,
        ].join("\n");

        await fs.writeFile(filePath, mdcContent, "utf-8");
        return path.relative(cwd, filePath);
    } else {
        // Windsurf: project-root .windsurfrules (no scoped alternative)
        const filePath = path.join(cwd, ".windsurfrules");
        await fs.writeFile(filePath, body, "utf-8");
        return path.relative(cwd, filePath);
    }
}
