/**
 * OpenClaw Stage Adapter
 *
 * Merges the combo's tal persona + dance rules (including skills)
 * into a single `soul.md` file at the project root for OpenClaw.
 */

import fs from "fs/promises";
import path from "path";

export interface OpenClawStageInput {
    /** Tal persona thinking/description */
    persona: string;
    /** Full dance rules text (includes skills if present) */
    rules: string;
    /** Optional act description */
    actDescription?: string;
}

/**
 * Write a unified rules file for OpenClaw in soul.md.
 */
export async function applyOpenClawStage(
    cwd: string,
    input: OpenClawStageInput
): Promise<string> {
    const filename = "soul.md";
    const filePath = path.join(cwd, filename);

    const sections: string[] = [
        `# Dance of Tal — AI Behavior Rules`,
        "",
        `## Persona`,
        input.persona,
        "",
        `## Rules`,
        input.rules,
    ];

    if (input.actDescription) {
        sections.push("", `## Workflow`, input.actDescription);
    }

    sections.push(
        "",
        `<!-- Generated by Dance of Tal (dot) — do not edit manually -->`
    );

    await fs.writeFile(filePath, sections.join("\n"), "utf-8");
    return path.relative(cwd, filePath);
}
