import { describe, it, expect } from "vitest";
import { applyOpenClawStage, OpenClawStageInput } from "./openclaw.js";
import fs from "fs/promises";
import path from "path";
import os from "os";

describe("applyOpenClawStage", () => {
    it("should generate soul.md file for openclaw variant", async () => {
        const tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), "dot-test-"));

        const input: OpenClawStageInput = {
            persona: "You are an expert engineer.",
            rules: "- Always write tests\n- Be concise",
            actDescription: "Review the PR",
        };

        const returnedPath = await applyOpenClawStage(tmpDir, input);
        const expectedFileName = "soul.md";

        // Should return relative path (in this case just the filename since cwd is the same)
        expect(returnedPath).toBe(expectedFileName);

        // File should exist
        const fullPath = path.join(tmpDir, expectedFileName);
        const content = await fs.readFile(fullPath, "utf-8");

        // Verify content sections
        expect(content).toContain("# Dance of Tal — AI Behavior Rules");
        expect(content).toContain("## Persona\nYou are an expert engineer.");
        expect(content).toContain("## Rules\n- Always write tests\n- Be concise");
        expect(content).toContain("## Workflow\nReview the PR");
        expect(content).toContain("<!-- Generated by Dance of Tal (dot) — do not edit manually -->");

        // Cleanup
        await fs.rm(tmpDir, { recursive: true, force: true });
    });
});
