/**
 * OpenCode Stage Adapter
 *
 * Writes to `.opencode/rules/dot-<combo>.md` — a plugin-based
 * rule file that OpenCode loads conditionally from the rules directory.
 */

import fs from "fs/promises";
import path from "path";

export interface OpenCodeStageInput {
    /** Tal persona thinking/description */
    persona: string;
    /** Full dance rules text (includes skills if present) */
    rules: string;
    /** Optional act description */
    actDescription?: string;
    /** Combo name for file naming */
    comboName?: string;
}

/**
 * Write a scoped rule file for OpenCode.
 */
export async function applyOpenCodeStage(
    cwd: string,
    input: OpenCodeStageInput
): Promise<string> {
    const comboSlug = input.comboName || "combo";
    const dir = path.join(cwd, ".opencode", "rules");
    await fs.mkdir(dir, { recursive: true });

    const filename = `dot-${comboSlug}.md`;
    const filePath = path.join(dir, filename);

    const sections: string[] = [
        `# Dance of Tal — AI Behavior Rules`,
        "",
        `## Persona`,
        input.persona,
        "",
        `## Rules`,
        input.rules,
    ];

    if (input.actDescription) {
        sections.push("", `## Workflow`, input.actDescription);
    }

    sections.push(
        "",
        `<!-- Generated by Dance of Tal (dot) — do not edit manually -->`
    );

    await fs.writeFile(filePath, sections.join("\n"), "utf-8");
    return path.relative(cwd, filePath);
}
